/* Spend Tracker V23 Settings module
   Settings-only presentation layer. Existing data/business functions are reused.
*/
(function(){
  'use strict';
  const PROFILE_KEY='spend_tracker_profile_v18_1';
  const photoKeys=['spend_tracker_profile_photo','spend_tracker_profile_photo_v1'];
  const $=id=>document.getElementById(id);
  const safe=(fn,fb)=>{try{return fn()}catch(e){return fb}};
  const escv=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const getProfile=()=>safe(()=>window.V20Profile?.get(),null)||{name:localStorage.getItem(PROFILE_KEY+'_name')||'Abhishek',email:localStorage.getItem(PROFILE_KEY+'_email')||'',photo:photoKeys.map(k=>localStorage.getItem(k)).find(Boolean)||''};
  const initials=n=>String(n||'A').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'A';
  function settingsRoot(){return document.querySelector('#mmore.active,#wmore.active')||document.querySelector('#mmore,#wmore')}
  function themeController(){return window.V21ThemeController}
  function renderAvatar(el,p){if(!el)return;el.style.backgroundImage=p.photo?`url(${p.photo})`:'';el.style.backgroundSize='cover';el.style.backgroundPosition='center';el.textContent=p.photo?'':initials(p.name)}
  function profileHeader(){const p=getProfile();return `<div class="v23-profile-hero"><div class="v23-avatar-wrap"><button class="v23-avatar" type="button" onclick="document.getElementById('v23ProfilePhoto')?.click()" aria-label="Change profile photo">${p.photo?`<img src="${escv(p.photo)}" alt="Profile photo">`:`<span>${escv(initials(p.name))}</span>`}<i>✎</i></button><input class="v23-hidden-photo" id="v23ProfilePhoto" type="file" accept="image/*" onchange="v23PhotoSelected(this)"></div><div class="v23-profile-name-row"><h1>${escv(p.name||'Abhishek')}</h1><button class="v23-pencil" type="button" onclick="v23ToggleProfileEdit(true)" aria-label="Edit profile">✎</button></div><div class="v23-profile-email">${escv(p.email||'No email added')}</div><div class="v23-profile-tag">Your tracker. Your rules.</div></div>`}
  function profileEditor(){const p=getProfile();return `<div class="v23-profile-editor" id="v23ProfileEditor" hidden><div class="v23-field"><label for="v23Name">Name</label><input id="v23Name" autocomplete="name" value="${escv(p.name||'Abhishek')}"></div><div class="v23-field"><label for="v23Email">Email</label><input id="v23Email" autocomplete="email" type="email" value="${escv(p.email||'')}"></div><div class="v23-editor-actions"><button class="secondary" type="button" onclick="v23ToggleProfileEdit(false)">Cancel</button><button class="primary" type="button" onclick="v23SaveProfile()">Save</button></div><button class="v23-remove-photo" type="button" onclick="removeProfilePhoto();v23ToggleProfileEdit(false)">Remove profile photo</button></div>`}
  function row(icon,title,sub,body,open=false,cls=''){return `<details class="v23-setting ${cls}" ${open?'open':''}><summary><span class="v23-setting-icon">${icon}</span><span class="v23-setting-copy"><b>${title}</b><small>${sub}</small></span><span class="v23-chevron">›</span></summary><div class="v23-setting-body">${body}</div></details>`}
  function manageRows(){
    const cats=(state.money.cats||[]).map(c=>`<div class="v23-manage-row"><span>${escv((c.icon||'💸')+' '+c.name)}</span><button class="mini" onclick="openCategory('${c.id}')">Edit</button><button class="mini danger" onclick="deleteCategory('${c.id}')">Delete</button></div>`).join('')||'<div class="empty">No categories.</div>';
    const methods=(state.money.methods||[]).map(m=>`<div class="v23-manage-row"><span>💳 ${escv(m.name)} <small>${escv(m.type||'')}</small></span><button class="mini" onclick="openMethod('${m.id}')">Edit</button><button class="mini danger" onclick="deleteMethod('${m.id}')">Delete</button></div>`).join('')||'<div class="empty">No payment methods.</div>';
    const accounts=(state.money.incomeAccounts||[]).map(a=>`<div class="v23-manage-row"><span>🏦 ${escv(a.name)}</span><button class="mini" onclick="openIncomeAccount('${a.id}')">Edit</button><button class="mini danger" onclick="deleteIncomeAccount('${a.id}')">Delete</button></div>`).join('')||'<div class="empty">No income accounts.</div>';
    return {cats,methods,accounts};
  }
  function wealthManage(){
    const w=state.wealth||{};
    const block=(title,items,edit,del,icon,subFn)=>`<div class="v23-subsection"><div class="v23-subhead"><b>${icon} ${title}</b><button class="link" onclick="${edit}()">＋ Add</button></div>${items.length?items.map(x=>`<div class="v23-manage-row"><span><b>${escv(x.label)}</b><small>${escv(subFn(x))}</small></span><button class="mini" onclick="${edit}('${x.id}')">Edit</button>${del?`<button class="mini danger" onclick="${del}('${x.id}')">Delete</button>`:''}</div>`).join(''):'<div class="empty">Nothing added yet.</div>'}</div>`;
    return [
      block('Mutual funds',(w.mfs||[]).map(x=>({...x,label:x.name})),"openMf","deleteMf",'📈',x=>money(x.value||0)),
      block('FDs',(w.fds||[]).map(x=>({...x,label:(x.bank||'FD')+' FD'})),"openFd","deleteFd",'🏧',x=>money(x.value||x.principal||0)),
      block('Stocks / ETFs',(w.stocks||[]).map(x=>({...x,label:x.name})),"openStock","deleteStock",'📊',x=>money(x.value||0)),
      block('Loans',(w.loans||[]).map(x=>({...x,label:x.name})),"openLoan","deleteLoan",'🏦',x=>money(x.outstanding||0)),
      block('Other assets',(w.assets||[]).map(x=>({...x,label:x.name})),"openAsset","deleteAsset",'🏠',x=>money(x.value||0)),
      block('Money owed',(w.debts||[]).map(x=>({...x,label:x.person})),"openDebt","deleteDebt",'🤝',x=>money(x.remaining||x.amount||0)),
      `<div class="v23-subsection"><div class="v23-subhead"><b>🧾 EPFO</b><button class="link" onclick="openEpfo()">Edit</button></div><div class="v23-manage-row"><span><b>EPFO balance</b><small>${money(w.epfo?.balance||0)}</small></span></div></div>`,
      `<div class="v23-subsection"><div class="v23-subhead"><b>🎯 Financial milestones</b><button class="link" onclick="openMilestone()">＋ Add</button></div>${(w.milestones||[]).length?(w.milestones||[]).map(x=>`<div class="v23-manage-row"><span><b>${escv(x.name)}</b><small>${money(x.current||0)} / ${money(x.target||0)}</small></span><button class="mini" onclick="openMilestone('${x.id}')">Edit</button><button class="mini danger" onclick="deleteMilestone('${x.id}')">Delete</button></div>`).join(''):'<div class="empty">No milestones yet.</div>'}</div>`
    ].join('');
  }
  function appearanceBody(){return `<div class="v23-option-label">Appearance</div><div class="v21-appearance-row"><button class="v21-appearance-day" type="button">☀ Day</button><button class="v21-appearance-night" type="button">☾ Night</button><button class="v21-appearance-auto" type="button">Auto</button></div><div class="v23-option-label">Color theme</div><div class="theme-preset-grid"></div><div class="v23-option-label">Text size</div><div class="text-scale-row"><button id="textSmall" onclick="setTextScale('small')">Small</button><button id="textNormal" onclick="setTextScale('normal')">Normal</button><button id="textLarge" onclick="setTextScale('large')">Large</button></div>`}
  function personalizationBody(){const p=typeof ensurePersonal==='function'?ensurePersonal():(state.personalization??={enabled:true,funny:true,facts:true});p.humour=p.humour!==false;p.motivation=p.motivation!==false;p.tips=p.tips!==false;p.celebration=p.celebration!==false;return `<div class="v23-personal-intro">Choose what the Fun Engine is allowed to show. The floating 🎲 uses the same rules.</div><label class="v23-switch-row"><span><b>Personalized experience</b><small>Enable Fun Engine messages</small></span><input type="checkbox" ${p.enabled!==false?'checked':''} onchange="setPersonalization('enabled',this.checked)"></label><label class="v23-switch-row"><span><b>Funny / sarcastic</b><small>Light jokes and wallet chaos</small></span><input type="checkbox" ${p.funny!==false?'checked':''} onchange="setPersonalization('funny',this.checked)"></label><label class="v23-switch-row"><span><b>Finance facts</b><small>Useful money facts</small></span><input type="checkbox" ${p.facts!==false?'checked':''} onchange="setPersonalization('facts',this.checked)"></label><label class="v23-switch-row"><span><b>Humour</b><small>Playful lines without finance facts</small></span><input type="checkbox" ${p.humour!==false?'checked':''} onchange="setPersonalization('humour',this.checked)"></label><label class="v23-switch-row"><span><b>Motivation</b><small>Progress and consistency messages</small></span><input type="checkbox" ${p.motivation!==false?'checked':''} onchange="setPersonalization('motivation',this.checked)"></label><label class="v23-switch-row"><span><b>Finance tips</b><small>Short practical guidance</small></span><input type="checkbox" ${p.tips!==false?'checked':''} onchange="setPersonalization('tips',this.checked)"></label><label class="v23-switch-row"><span><b>Celebrations</b><small>Milestones and positive progress</small></span><input type="checkbox" ${p.celebration!==false?'checked':''} onchange="setPersonalization('celebration',this.checked)"></label>`}
  function backupBody(){return `<div class="v23-backup-note">JSON is the complete restore format. CSV is for transactions in Excel/Sheets. Import and Merge never clear data unless you explicitly choose Restore.</div><div class="v23-backup-actions"><button onclick="backupData()"><b>💾 Full backup</b><small>Complete JSON snapshot</small></button><button onclick="exportCSV()"><b>▤ CSV export</b><small>Transactions for Excel/Sheets</small></button><button onclick="importData()"><b>⬆ Restore</b><small>Replace from a backup</small></button><button onclick="mergeData()"><b>＋ Merge</b><small>Add backup records</small></button><button onclick="backupToCloudShare()"><b>☁ Share backup</b><small>Send through device share</small></button></div>`}
  function renderSettings(root){
    if(!root)return;
    const p=getProfile(),m=manageRows();
    const title=app.mode==='wealth'?'Wealth Settings':'Profile & Settings';
    root.className='screen active v23-settings';
    root.innerHTML=`<div class="v23-settings-page"><div class="v23-settings-title"><span>Profile &amp; Settings</span><small>${app.mode==='wealth'?'Wealth control center':'Your money, your rules.'}</small></div>${profileHeader()}<div class="v23-settings-list">${row('👤','Profile Details','Name, email and profile photo',`<div class="v23-profile-inline">${profileEditor().replace(' id="v23ProfileEditor"',' id="v23ProfileEditorInline"')}</div>`,false,'profile-setting')}${row('🎨','Appearance & Text','Day/night, themes and text size',appearanceBody(),false,'appearance-setting')}${row('🧩','Money Categories','Add, edit or remove spending categories',`<div class="v23-manage-list">${m.cats}</div><button class="v23-add-row" onclick="openCategory()">＋ Add category</button>`,false,'money-setting')}${row('💳','Payment Methods','Cards, bank accounts, cash and UPI',`<div class="v23-manage-list">${m.methods}</div><button class="v23-add-row" onclick="openMethod()">＋ Add payment method</button>`,false,'money-setting')}${row('🏦','Income Accounts','Accounts used for income entries',`<div class="v23-manage-list">${m.accounts}</div><button class="v23-add-row" onclick="openIncomeAccount()">＋ Add account</button>`,false,'money-setting')}${row('📈','Wealth Setup','Funds, FDs, stocks, loans, debts and goals',wealthManage(),false,'wealth-setting')}${row('💾','Backup & Transfer','Export, restore, merge and share',backupBody(),false,'backup-setting')}${row('🧠','Personalization','Control the Fun Engine message types',personalizationBody(),false,'personal-setting')}${row('🗑️','Reset App Data','Delete local Money + Wealth data',`<div class="v23-danger-note">This permanently deletes current local app data. Export a backup first.</div><button class="danger-wide v23-reset" onclick="resetProfile()">Reset all data</button>`,false,'danger-setting')}</div><div class="v23-settings-footer">Spend Tracker · Settings</div></div>`;
    syncSettings(root);
  }
  function syncSettings(root){
    const p=getProfile();root.querySelectorAll('.v23-avatar').forEach(a=>renderAvatar(a,p));
    const tc=themeController();if(tc?.setTheme){root.querySelectorAll('.theme-preset').forEach(b=>b.onclick=()=>tc.setTheme(b.dataset.theme));}
    root.querySelectorAll('.v21-appearance-day').forEach(b=>b.onclick=()=>tc?.setAppearance('day'));
    root.querySelectorAll('.v21-appearance-night').forEach(b=>b.onclick=()=>tc?.setAppearance('night'));
    root.querySelectorAll('.v21-appearance-auto').forEach(b=>b.onclick=()=>tc?.setAppearance('auto'));
    safe(()=>window.renderTheme());safe(()=>window.syncThemeButtons?.());
    root.querySelectorAll('details').forEach(d=>d.addEventListener('toggle',()=>{if(d.open)root.querySelectorAll('details[open]').forEach(o=>{if(o!==d)o.open=false})},{once:false}));
  }
  function updatePhotoPreview(data){const root=settingsRoot();if(!root)return;const av=root.querySelector('.v23-avatar');if(av){av.innerHTML=`<img src="${escv(data)}" alt="Profile photo"><i>✎</i>`}}
  window.v23PhotoSelected=function(input){const f=input?.files?.[0];if(!f)return;if(!f.type.startsWith('image/'))return alert('Choose an image.');const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=512,s=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*s));c.height=Math.max(1,Math.round(img.height*s));c.getContext('2d').drawImage(img,0,0,c.width,c.height);const data=c.toDataURL('image/jpeg',.86);if(window.V20Profile?.set)window.V20Profile.set({photo:data});else localStorage.setItem(photoKeys[0],data);updatePhotoPreview(data);};img.src=r.result};r.readAsDataURL(f)};
  window.v23ToggleProfileEdit=function(show){const root=settingsRoot();if(!root)return;const section=root.querySelector('.profile-setting');const editor=root.querySelector('.profile-setting .v23-profile-editor');if(section&&show)section.open=true;if(editor)editor.hidden=!show;if(show)root.querySelector('#v23Name')?.focus();}
  window.v23SaveProfile=function(){const root=settingsRoot();if(!root)return;const n=(root.querySelector('#v23Name')?.value||'').trim(),e=(root.querySelector('#v23Email')?.value||'').trim();if(!n)return alert('Enter your name.');if(e&&!/^\S+@\S+\.\S+$/.test(e))return alert('Enter a valid email address.');if(window.V20Profile?.set)window.V20Profile.set({name:n,email:e});else{localStorage.setItem(PROFILE_KEY+'_name',n);localStorage.setItem(PROFILE_KEY+'_email',e)}renderSettings(root);}
  window.openMore=function(){if(app.mode==='wealth')app.wealthPage='more';else app.moneyPage='more';refresh();window.scrollTo({top:0,behavior:'smooth'});setTimeout(()=>renderSettings(settingsRoot()),0)};
  window.renderMore=function(){const root=settingsRoot();if(root)renderSettings(root)};
  const oldRefresh=window.refresh;
  if(oldRefresh&&!oldRefresh.__v23settings){window.refresh=function(){const r=oldRefresh.apply(this,arguments);setTimeout(()=>{const root=settingsRoot();if(root?.classList.contains('v23-settings'))renderSettings(root);},0);return r};window.refresh.__v23settings=true;}
  function patchFunPrefs(){const old=window.setPersonalization;if(old&&!old.__v23){window.setPersonalization=function(k,v){const p=typeof ensurePersonal==='function'?ensurePersonal():(state.personalization??={enabled:true,funny:true,facts:true});p[k]=!!v;save();safe(()=>renderMore());safe(()=>window.V21Fun?.context());};window.setPersonalization.__v23=true;}}
  function funPrefs(){const p=typeof ensurePersonal==='function'?ensurePersonal():(state.personalization??={enabled:true,funny:true,facts:true});p.humour=p.humour!==false;p.motivation=p.motivation!==false;p.tips=p.tips!==false;p.celebration=p.celebration!==false;return p}
  function funAllowed(kind){const p=funPrefs();if(p.enabled===false)return false;if(kind==='funny'&&p.funny===false)return false;if(kind==='fact'&&p.facts===false)return false;if(kind==='humour'&&p.humour===false)return false;if(kind==='motivation'&&p.motivation===false)return false;if(kind==='tip'&&p.tips===false)return false;if(kind==='celebration'&&p.celebration===false)return false;return true}
  function funPickV23(event){if(!funAllowed('money'))return null;const lib=window.SpendTrackerFunLibrary?.all?.()||[];let pool=lib.filter(x=>x.event===event&&funAllowed(x.kind));if(!pool.length)pool=lib.filter(x=>x.event==='context'&&funAllowed(x.kind));if(!pool.length)return null;const store=safe(()=>JSON.parse(localStorage.getItem('spend_tracker_v21_fun')||'{}'),{}),recent=Array.isArray(store.recent)?store.recent:[],fresh=pool.filter(x=>!recent.includes(x.id));const x=(fresh.length?fresh:pool)[Math.floor(Math.random()*(fresh.length?fresh.length:pool.length))];store.recent=[...recent.filter(id=>id!==x.id),x.id].slice(-18);store.last=x.id;localStorage.setItem('spend_tracker_v21_fun',JSON.stringify(store));const locale=(store.locale||navigator.language||'en').toLowerCase().startsWith('hi')?'hi':'en';return {...x,text:x.text?.[locale]||x.text?.en||''}}
  function showFunV23(x){if(!x)return;['globalMessage','surprisePreview','wealthSurprisePreview'].forEach(id=>{const e=$(id);if(e)e.textContent=x.text});const bf=$('brainFoodText');if(bf)bf.textContent=x.text;const bi=$('brainFoodIcon');if(bi)bi.textContent=x.kind==='wealth'?'📈':'🧠';const bt=$('brainFoodTag');if(bt)bt.textContent=app.mode==='wealth'?'WEALTH BRAIN FOOD':'MONEY BRAIN FOOD';}
  function patchDiceFun(){const api=window.V21Fun||(window.V21Fun={});api.dice=function(){const x=funPickV23('dice');showFunV23(x);window.openBrainFood?.();showFunV23(x);return x};api.context=function(){const x=funPickV23('context');showFunV23(x);return x};api.transaction=function(tx){const event=tx?.type==='income'?'income':tx?.type==='transfer'?'transfer':'expense';const x=funPickV23(event);showFunV23(x);return x};api.library=()=>window.SpendTrackerFunLibrary?.all?.()||[];window.V21Fun=api;window.showSurpriseMessage=function(){const x=funPickV23('dice')||funPickV23('context');showFunV23(x);return x};}
  function boot(){patchFunPrefs();patchDiceFun();const root=settingsRoot();if(root&&root.classList.contains('v23-settings'))renderSettings(root)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
